version: "3"
services:
  maplestory:
    build: .
    depends_on:
      - db
    ports:
      - "8484:8484"
      - "7575:7575"
      - "7576:7576"
      - "7577:7577"
    volumes:
      - ./config.yaml:/mnt/config.yaml
      - ./scripts:/mnt/scripts
    networks:
      - backend
    environment:
      WAIT_HOSTS: db:3306

  db:
    image: mariadb:10.11.5
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_DATABASE: "heavenms"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "fahoi"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

networks:
  backend:
    driver: bridge
